# Which backend each 3-letter code should use
[database_map]
XYZ = "postgres_xyz"
MNO = "postgres_mno"

# PostgreSQL groups
[postgres_xyz]
user = "postgres"
password = "postgres"
host = "localhost"
port = 5433
database = "xyz"
api_url = "http://127.0.0.1:8000"

[postgres_mno]
user = "postgres"
password = "postgres"
host = "localhost"
port = 5433
database = "mno"
api_url = "http://127.0.0.1:8000"